### ISSUE TITLE
Performance benchmark for loki and cLoki comparison

### ISSUE THREAD

**Issue by xuanyue202** [metrico/qryn#149]
Great project! Do you have any plan to construct a performance benchmark to compare loki and cLoki? It would be very helpful to help people like me to decide whether to use cLoki over loki.

**Comment by lmangani** [comment]
@xuanyue202 thanks for the kind words and yes, we're working on our benchmarking suite as well as schema updates.
Since the two projects support the same APIs, once the above is completed we should be able to draw interesting comparisons on the various aspects, although our focus is on maximising the ClickHouse native performance aspects.

Let's keep this thread open for future updates.

**Comment by xuanyue202** [comment]
Thanks for the update. Looking forward to that!

**Comment by lmangani** [comment]
Feel free to reopen if still interested for 3.x
