### ISSUE TITLE
Why AGPL?

### ISSUE THREAD

**Issue by justinabrahms** [metrico/qryn#220]
Hey metrico folks.

I'm curious.. did you choose AGPL because this is a business choice? Or because one of your dependencies is AGPL and you have to release your code as AGPL? Is there hope for a dual-license into something like an Apache 2.0?

**Comment by lmangani** [comment]
Hello @justinabrahms 

Thanks for opening this issue - its a great discussion topic, and a necessary one. 

We believe at this early stage AGPLv3 protects our software best from being forked and extended by 3rd parties without benefiting the entire community back, since it's really a two-way community we're trying to build around our stack. %GPL licenses also discourage usage by corporations which not invested in supporting open-source culturally (and ban it, too)

This being said, we do provide integrators, developers and customers with an SLA supported non-GPL license to our qryn go stack (qryn:cloud) to sponsor our development and boost our aggressive polyglot roadmap. Once we reach stability and financial balance, we have all intentions to change towards Apache2 or MIT licenses as we do for other projects we maintain and manage. Could you expand on your preferences as a user or integrator? What would your proposal be?

Thanks!

**Comment by justinabrahms** [comment]
Yeah, I'm looking around for things like a Loki logql parser that's not agpl (else we'd use the official one from Grafana). 

I noticed y'all already forked one of their repos and kept it going on an apache license ( https://github.com/metrico/loki-apache ). 

As we're looking at an expanded offering, we came across this repo, but cannot use it at work due to the agpl license.

**Comment by lmangani** [comment]
@justinabrahms we can help with that. contact us at info@metrico.in for licensing details
