### ISSUE TITLE
qryn distributed schema

### ISSUE THREAD

**Issue by doonydoo** [metrico/qryn#329]
Hello!
tell me please, qryn is a stateless app? Can I split the application replicas into geographically separated data centers?
Will qryn work correctly for reading and writing if it is located in different k8s  clusters or data centers? Like in scheme below:

![image](https://github.com/metrico/qryn/assets/79003398/5b50721a-acae-4227-b335-5ef7add937ea)

**Comment by lmangani** [comment]
Hello @doonydoo 
Yes - qryn is stateless and multiple instances can be deployed in parallel to achieve the desired capacity or distribution. Since reads/writes are not directly connected, the schema is generally a valid one, although very generic. qryn also supports more advanced insert methods directly to clickhouse using our otel-collector to bypass the writers and only spawn readers.

**Comment by doonydoo** [comment]
@lmangani thanks a lot!
