### ISSUE TITLE
Bug basic auth status code

### ISSUE THREAD

**Issue by rerime** [metrico/qryn#331]
Setup envs:
```
QRYN_LOGIN: qq
QRYN_PASSWORD: qq
```

```
curl  localhost:3100
{"statusCode":500,"error":"Internal Server Error","message":"Internal Server Error"}
```

I guess it should be 401

Also this attempts do not logging.

**Comment by lmangani** [comment]
The information is not sufficient. Please make a small effort to always include the context of your reports and include everything, full logs, the request causing the error, etc.

**Comment by lmangani** [comment]
Thanks! Please enable the DEBUG parameter, we need to see the full qryn init logs to know if its even ready to accept requests. Does ingestion work at the same time this error happens? Have you tried with a password longer than 2 chars?

**Comment by rerime** [comment]
@lmangani  Reproduce bug and feel free to modify any params that you like for debug on your side.

**Comment by rerime** [comment]
@lmangani  same bug

```
docker run --rm -d --name qryn --network=qryn -e CLICKHOUSE_SERVER=clickhouse -e API_URL=http://clickhouse:3100 -e QRYN_LOGIN=qq -e QRYN_PASSWORD=qq -p 3100:3100 qxip/qryn:latest
```

**Comment by lmangani** [comment]
So wait, you were requesting about a *wrong* auth the whole time? I thought you were getting 500 with the *correct* authentication based on your examples. Oh well now it makes more sense. There's no 401 here because the pair check is performed ahead of the actual http authentication - hence the generic error. I guess we can add a full handler if this is useful for consistence.

**Comment by rerime** [comment]
@lmangani  yes
