### ISSUE TITLE
Can I use qryn for aggregating logs of my clickhouse cluster?

### ISSUE THREAD

**Issue by anvaari** [metrico/qryn#340]
Hi team
Sorry, i think i'm little confused. I can't find out whether `qryn` can be used to monitor aggregated clickhouse logs in Loki ?

**Comment by lmangani** [comment]
Hello @anvaari 

`qrys` is a full blown loki/tempo replacement - and yes qryn can most definitely ingest, search and aggregate clickhouse's own logs, metrics and traces as per any other agent/source we support in our stack. We have several methods using ClickHouse MV's to stash data into qryn APIs and since we're Loki compatible, those recipes *should* work with any LogQL API just the same way.  So if you want to keep the loki functionality without installing/using Grafana Loki and you want all your data to stay in ClickHouse, qryn might be a good option.

I hope this helps.
