### ISSUE TITLE
Open source qryn-go

### ISSUE THREAD

**Issue by tomershafir** [metrico/qryn#341]
Hey, do you plan to open source qryn-go? if so any eta?

**Comment by lmangani** [comment]
Hello @tomershafir we're 100% going to opensource the next qryn-go version with multiple backend support, but there is no ETA yet. The sooner the better but this really only depends on the project's ability to support itself financially and stay open source. Since despite the efforts and the decent amount of users and installations we have zero donations and no backers, we are currently funding our development efforts through the [qryn.cloud service](https://qryn.cloud).

**Comment by tomershafir** [comment]
thx for the quick resp :) hope you'll make it through!
