### ISSUE TITLE
QRYN 3.0 release 

### ISSUE THREAD

**Issue by akvlad** [metrico/qryn#365]
Release Roadmap:

- [x] bun runtime support
- [x] prometheus wasm support
- [x] limited traceQL support
- [x] grafana >10.0.1 compatibility https://github.com/metrico/qryn/issues/360
- [x] upgrade [qryn-otel-collector](https://github.com/metrico/otel-collector) to latest opentelemetry
- [x] clickhouse cluster support settings

**Comment by lbogdan** [comment]
Is there an up-to-date changelog anywhere?

The only one I could find is [the one in the Wiki](https://github.com/metrico/qryn/wiki/Changelog), which was last updated December last year for `v2.2.0`, current version being `v2.4.4`, released 5 days ago.

**Comment by lmangani** [comment]
Hello @lbogdan the above is a changelog for 3.0 with the major changes. Every single 2.x release has a PR. 
What were you looking for specifically?

**Comment by lbogdan** [comment]
> What were you looking for specifically?

Just a single page that I can quickly skim over to figure out the recent project's progress / direction.

**Comment by lmangani** [comment]
3,0 roadmap above represents the project's progress / direction at this time. We generally only list major changes, since most are issue/report based (fixes) all the code its OSS users can dig deeper at will. Note qryn 2.x releases were based on individual PRs (220+ releases) functioning as changelog, while qryn 3.x will be based on aggregated PR releases, making it easier to maintain a formal changelog on qryn.dev 👍
